# HW01 <font color=red>(제출기한-4월9일 자정)</font>
NumPy 이해도 평가를 위한 문제입니다. 
- Loop를 사용하면 감점입니다. (즉, ufunc을 활용할 것)
- Random을 바꿔보며 테스트해 보기 바랍니다. 

제출시 다음 사항에 유의하기 바랍니다.
- 텍스트 셀에 설명되어 있는 각 문항을 잘 읽은 뒤, 코드 셀에 적절한 코드를 작성합니다.
- 작성 후 파일명에 ``학번``을 자신의 학번으로 고친 후 ULMS 해당과제 제출란에 업로드합니다.


In [0]:
import numpy as np
rng=np.random.RandomState(100)

### 문제1
0이상 100이하의 임의의 정수들로 구성되는 100행 5열의 2차원 numpy array인 ``score``를 생성하시오.
<font color=red>(단, 위 rng를 사용할 것)</font>

In [0]:
### 답안을 작성하시오. 

score = rng.randint(101,size = (100,5))

In [4]:
### 지우지 마시오.
score

array([[  8,  24,  67,  87,  79],
       [ 48,  10,  94,  52,  98],
       [ 53,  66,  98,  14,  34],
       [ 24,  15, 100,  60,  58],
       [ 16,   9,  93,  86,   2],
       [ 27,   4,  31,   1,  13],
       [ 83, 100,   4,  91,  59],
       [ 67,   7,  49,  47,  65],
       [ 61,  14,  55,  71,  80],
       [  2,  94,  19,  98,  63],
       [ 53,  27,  56,  30,  48],
       [ 47,  39,  38,  44,  18],
       [ 64,  56,  34,  53,  74],
       [ 17,  72,  13,  30,  17],
       [ 53,  68,  50,  91,  91],
       [ 83,  53,  78,   0,  13],
       [ 57,  76,   3,  70,   3],
       [ 84,  79,  10,  87,  60],
       [  3,  48,  52,  43,  36],
       [  5,  71,  38,  86,  94],
       [ 98,  42,  84,  95,  76],
       [ 33,  58,  42,  22,   0],
       [ 55,  98,  19,  53,  68],
       [ 62,  50,  68,  35,  23],
       [  9,  48,  21,  25,  54],
       [  6,  37,  58,  39,  94],
       [ 51,  30,  66,  24,  55],
       [ 17,  45,  89,  45,  35],
       [ 16,  12,  86,  82,  67],
       [ 92,  

### 문제2
지금부터 ``score``가 100명의 학생들의 국어, 영어, 수학, 과학, 사회 점수를 뜻한다고 가정하자.

이제 5개 과목의 평균점수를 뜻하는 ``avg_subject`` array(1차원)를 생성하시오. 

In [0]:
### 답안을 작성하시오. 
sum_subject = np.add.reduce(score)
avg_subject = sum_subject/100.0

In [9]:
### 지우지 마시오.
avg_subject

array([45.5 , 53.17, 51.43, 53.54, 51.39])

### 문제3
학생별 평균점수를 뜻하는 ``avg_student`` array(1차원)를 생성하시오. 

In [0]:
### 답안을 작성하시오. 
sum_student = np.add.reduce(score,axis=1)
avg_student = sum_student.reshape(100,1)/5.0

In [11]:
### 지우지 마시오.
avg_student

array([[53. ],
       [60.4],
       [53. ],
       [51.4],
       [41.2],
       [15.2],
       [67.4],
       [47. ],
       [56.2],
       [55.2],
       [42.8],
       [37.2],
       [56.2],
       [29.8],
       [70.6],
       [45.4],
       [41.8],
       [64. ],
       [36.4],
       [58.8],
       [79. ],
       [31. ],
       [58.6],
       [47.6],
       [31.4],
       [46.8],
       [45.2],
       [46.2],
       [52.6],
       [45. ],
       [44.2],
       [57.2],
       [60.2],
       [49.4],
       [77.4],
       [21.6],
       [57. ],
       [49.6],
       [57.8],
       [64. ],
       [34.8],
       [40. ],
       [36.6],
       [51.2],
       [52. ],
       [68.6],
       [63.8],
       [52. ],
       [72.8],
       [38.6],
       [25.6],
       [54.8],
       [69.8],
       [68.8],
       [43.4],
       [47.6],
       [44. ],
       [49.2],
       [57.4],
       [49. ],
       [48. ],
       [36.6],
       [74.2],
       [31.4],
       [39. ],
       [46.8],
       [49

### 문제4
100명 중 row의 index가 짝수인 학생은 여학생, 홀수인 학생은 남학생이라고 할 때, 
여학생 전체의 5개과목별 평균점수를 뜻하는 ``avg_female`` array(1차원)을 구하시오.

In [0]:
### 답안을 작성하시오. 

female = score[::2,::]
avg_female = female.mean(0)

In [7]:
### 지우지 마시오.
avg_female

array([44.32, 54.82, 52.86, 58.24, 56.46])

### 문제5
마찬가지로 남학생 전체의 5개과목별 평균점수를 뜻하는 ``avg_male`` array(1차원)을 구하시오.

In [0]:
### 답안을 작성하시오. 

male=score[1::2,::]
avg_male = male.mean(0)

In [14]:
### 지우지 마시오.
avg_male

array([46.68, 51.52, 50.  , 48.84, 46.32])

### 문제6

$\frac{\text{avg_female} + \text{avg_male}}{2}$ 결과를 ``avg_all`` array 변수에 저장하시오.

(``avg_all``의 결과는 ``avg_subject``와 같아야 한다.)

In [0]:
### 답안을 작성하시오. 
avg_all = (avg_female+avg_male)/2.0

In [16]:
### 지우지 마시오.
avg_all

array([45.5 , 53.17, 51.43, 53.54, 51.39])

### 문제7
각 점수가 해당과목의 전체학생 평균으로부터 얼마나 차이가 나는지를 나타내는 ``score_dev`` array(2차원)를 생성하시오.
- score_dev의 shape는 score의 shape와 동일하다.
- 만약 점수가 30점이고 평균이 45점이면 그 차이는 $30-45=-15$ 점이다.


In [0]:
### 답안을 작성하시오. 
score_dev = score - avg_all

In [18]:
### 지우지 마시오.
score_dev

array([[-37.5 , -29.17,  15.57,  33.46,  27.61],
       [  2.5 , -43.17,  42.57,  -1.54,  46.61],
       [  7.5 ,  12.83,  46.57, -39.54, -17.39],
       [-21.5 , -38.17,  48.57,   6.46,   6.61],
       [-29.5 , -44.17,  41.57,  32.46, -49.39],
       [-18.5 , -49.17, -20.43, -52.54, -38.39],
       [ 37.5 ,  46.83, -47.43,  37.46,   7.61],
       [ 21.5 , -46.17,  -2.43,  -6.54,  13.61],
       [ 15.5 , -39.17,   3.57,  17.46,  28.61],
       [-43.5 ,  40.83, -32.43,  44.46,  11.61],
       [  7.5 , -26.17,   4.57, -23.54,  -3.39],
       [  1.5 , -14.17, -13.43,  -9.54, -33.39],
       [ 18.5 ,   2.83, -17.43,  -0.54,  22.61],
       [-28.5 ,  18.83, -38.43, -23.54, -34.39],
       [  7.5 ,  14.83,  -1.43,  37.46,  39.61],
       [ 37.5 ,  -0.17,  26.57, -53.54, -38.39],
       [ 11.5 ,  22.83, -48.43,  16.46, -48.39],
       [ 38.5 ,  25.83, -41.43,  33.46,   8.61],
       [-42.5 ,  -5.17,   0.57, -10.54, -15.39],
       [-40.5 ,  17.83, -13.43,  32.46,  42.61],
       [ 52.5 , -11.

### 문제8
``score_dev``에서 axis=0 방향으로 평균을 나타내는 ``avg_score_dev``를 구하시오. 

In [0]:
### 답안을 작성하시오. 

sum_tmp = np.sum(score_dev,axis=0)
avg_score_dev=sum_tmp/100.0

In [20]:
### 지우지 마시오.
avg_score_dev

array([ 0.00000000e+00, -6.25277607e-15, -1.77635684e-15, -7.24753590e-15,
        5.68434189e-15])

### 문제9
전체과목 평균을 기준으로 1등을 한 학생과 꼴등을 한 학생의 5개 과목 점수 array를 각각 ``student_best``, ``student_worst``에 각각 저장하시오. (1차원 array 변수) 

In [0]:
### 답안을 작성하시오. 

student_best = score[np.argmax(avg_student)]
student_worst = score[np.argmin(avg_student)]

In [22]:
### 지우지 마시오.
student_best, student_worst

(array([98, 42, 84, 95, 76]), array([27,  4, 31,  1, 13]))

### 문제10
모든 과목이 각 과목의 평균점수보다 높은 학생수를 구하여 ``no_elite`` 변수에 저장하시오.  

In [0]:
### 답안을 작성하시오. 

no_elite = np.count_nonzero(np.all(score_dev>0,axis=1))

In [24]:
### 지우지 마시오.
no_elite

3